<?php

namespace AppBundle\Repository;

/**
 * CheckinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CheckinRepository extends \Doctrine\ORM\EntityRepository
{
}
