<?php

namespace AppBundle\Repository;

/**
 * PointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointRepository extends \Doctrine\ORM\EntityRepository
{
    function findPointByIdPoste($id_poste){
        $query = $this->getEntityManager()->createQuery(
            'SELECT point FROM AppBundle:Point point
            INNER JOIN AppBundle:Poste poste
            WHERE point.id = poste.idPoint AND poste.id = :idPoste'
        )->setParameter('idPoste', $id_poste);
        
        return $query->getOneOrNullResult();
    }

    function findPointsByIdParcours($id_parcours){
        $query = $this->getEntityManager()->createQuery(
            'SELECT point FROM AppBundle:Point point
            INNER JOIN AppBundle:Trace t WITH point.idTrace = t.id
            INNER JOIN AppBundle:Parcours p WITH t.idParcours = p.id 
            WHERE p.id = :idParcours
            ORDER BY t.id, point.ordre ASC'
        )->setParameter('idParcours', $id_parcours);
        
        return $query->getResult();        
    }
}
