<?php

namespace AppBundle\Repository;

/**
 * PointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointRepository extends \Doctrine\ORM\EntityRepository
{
    function findPointByIdPoste($id_poste){
        $query = $this->getEntityManager()->createQuery(
            'SELECT point FROM AppBundle:Point point
            INNER JOIN AppBundle:Poste poste
            WHERE point.id = poste.idPoint AND poste.id = :idPoste'
        )->setParameter('idPoste', $id_poste);
        
        return $query->getOneOrNullResult();
    }
}
