<?php

namespace AppBundle\Repository;

/**
 * PrefPosteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrefPosteRepository extends \Doctrine\ORM\EntityRepository
{
}
