<?php

namespace AppBundle\Repository;

/**
 * PrefPosteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrefPosteRepository extends \Doctrine\ORM\EntityRepository
{
    function findPrefPostesByIdRaid($id_raid){
        $query = $this->getEntityManager()->createQuery(
            'SELECT p FROM AppBundle:PrefPoste p
            INNER JOIN AppBundle:Benevole b WITH b.id = p.idBenevole
            WHERE b.idRaid = :idRaid'
        )->setParameter('idRaid', $id_raid);
        return $query->getResult();
    }

    function findByIdRaidIdUser($id_raid, $id_user){
        $query = $this->getEntityManager()->createQuery(
            'SELECT p FROM AppBundle:PrefPoste p
            INNER JOIN AppBundle:Benevole b WITH b.id = p.idBenevole
            WHERE b.idRaid = :idRaid AND b.idUser = :idUser'
        )->setParameter('idRaid', $id_raid)
        ->setParameter('idUser', $id_user);
        return $query->getResult();
}
}
