<?php

namespace AppBundle\Repository;

/**
 * RaidRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RaidRepository extends \Doctrine\ORM\EntityRepository
{
    function findRaidsBenevolesByIdUser($id_user)
    {
        $query = $this->getEntityManager()->createQuery(
            'SELECT r FROM AppBundle:Raid r INNER JOIN AppBundle:Benevole b
            WHERE b.idUser = :idUser AND b.idRaid = r.id'
        )->setParameter('idUser', $id_user);
        
        return $query->getResult();
    }

    function findRaidsOrganisateursByIdUser($id_user)
    {
        $query = $this->getEntityManager()->createQuery(
            'SELECT r FROM AppBundle:Raid r INNER JOIN AppBundle:Organisateur o
            WHERE r.id = o.idRaid AND o.idUser = :idUser'
        )->setParameter('idUser', $id_user);
        
        return $query->getResult();
    }

    function findRaidsByIdParcours($id_parcours){
        $query = $this->getEntityManager()->createQuery(
            'SELECT r FROM AppBundle:Raid r INNER JOIN AppBundle:Parcours p
            WHERE r.id = p.idRaid AND (p.id = :idParcours OR p.idParcoursPere = :idParcours)'
        )->setParameter('idParcours', $id_parcours);
        
        return $query->getResult();
    }

    function findRaidsVisibleByIdUser($id_user){
        $query = $this->getEntityManager()->createQuery(
            'SELECT r FROM AppBundle:Raid r
            WHERE r.visibility = true 
            AND r NOT IN (
                SELECT r2 FROM AppBundle:Repartition rep
                INNER JOIN AppBundle:Benevole b WITH b.id = rep.idBenevole
                INNER JOIN AppBundle:Raid r2 WITH r2.id = b.idRaid
                WHERE b.idUser = :idUser
                GROUP BY r2.id
            )'
        )->setParameter('idUser',$id_user);
        
        return $query->getResult();
    }
}
